obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
#footprint: [[-0.2, -0.22], [-0.2, 0], [-0.2, 0.22], [0.2, 0.22], [0.2, 0], [0.2, -0.22]]
footprint: [[-0.22, 0.2], [0, 0.2], [0.22, 0.2], [0.22, -0.2], [0, -0.2], [-0.22, -0.2]]
#robot_radius: ir_of_robot
inflation_radius: 0.55

observation_sources: point_cloud_sensor

point_cloud_sensor: {sensor_frame: camera_depth_optical_frame, data_type: PointCloud2, topic: /camera/depth/color/points, marking: true, clearing: true}